config/routes.rb
RubyVault::Application.routes.draw do

  match "profile/:action" => "profile#:action", :as => :profile

  resources :accounts, :only => :index

  get "enrollment/state_identity", :as => :begin_enrollment
  post "enrollment/verify_identity"
  
  get "enrollment/choose_credentials", :as => :choose_credentials
  post "enrollment/create_account", :as => :create_account

  get "login" => "session#new", :as => :login
  post "session/create", :as => :create_session
  match "logout" => "session#destroy", :as => :logout

  resources :users

  root :to => "welcome#index", :as => :welcome

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end


  def create
    u = User.find_by_username(params[:username])
    if u
      if u.password == params[:password]
        session[:user_id] = u.id
        redirect_to welcome_path
      else
        flash.now[:message] = "Invalid password"
        render :action => :new
      end
    else
      flash.now[:message] = "Invalid username"
      render :action => :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to welcome_path
  end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/session/new.html.erb
<%= form_tag create_session_path do %>

  <% if flash[:message] %>
  <p class="error" >
    <%= flash[:message] %>
  </p>
  <% end %>

  <div class="field" >
    <%= label_tag :username %>
    <%= text_field_tag :username %>
  </div>
  
  
  <div class="field" >
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </div>

  <%= submit_tag "Login" %>
  
<% end %>