config/routes.rb
RubyVault::Application.routes.draw do

  match "profile/:action" => "profile#:action", :as => :profile

  resources :accounts, :only => :index

  get "enrollment/state_identity", :as => :begin_enrollment
  post "enrollment/verify_identity"
  
  get "enrollment/choose_credentials", :as => :choose_credentials
  post "enrollment/create_account", :as => :create_account

  get "login" => "session#new", :as => :login
  post "session/create", :as => :create_session
  match "logout" => "session#destroy", :as => :logout

  resources :users

  root :to => "welcome#index", :as => :welcome

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyVault</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


<header id="sitenav" >

    <nav id="authentication" >
      <ul>
        <% if logged_in? %>
          <li><%= link_to "Profile", profile_path(:view) %></li>
          <li><%= link_to "Logout", logout_path %></li>
        <% else %>
          <li><%= link_to "Enroll", begin_enrollment_path %></li>
          <li><%= link_to "Login", login_path %></li>
        <% end %>
      </ul>
    </nav>

    <nav>
      <ul>
        <li><%= link_to "Welcome", welcome_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Accounts", accounts_path %></li>
          <% if current_user.is_admin? %>
            <li><%= link_to "Users", users_path %></li>
          <% end %>
        <% end %>
      </ul>
    </nav>
</header>



<div id="content" >

  <%= yield %>
</div>

</body>
</html>